# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mcp_pb2 as mcp__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TestflingerControlStub:
    """============================================================
    TestflingerControl — gRPC service definition

    Authentication: every RPC requires a bearer token in the
    gRPC metadata header:

    Authorization: Bearer <token>

    Tokens are static secrets provisioned out-of-band (env vars,
    vault injection).  The server returns UNAUTHENTICATED if the
    header is missing or wrong, PERMISSION_DENIED if the token
    lacks privileges for the requested operation.
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveMachine = channel.unary_unary(
                '/mcp.v1.TestflingerControl/ReserveMachine',
                request_serializer=mcp__pb2.ReserveMachineRequest.SerializeToString,
                response_deserializer=mcp__pb2.ReserveMachineResponse.FromString,
                _registered_method=True)
        self.GetReservation = channel.unary_unary(
                '/mcp.v1.TestflingerControl/GetReservation',
                request_serializer=mcp__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=mcp__pb2.GetReservationResponse.FromString,
                _registered_method=True)
        self.WatchReservation = channel.unary_stream(
                '/mcp.v1.TestflingerControl/WatchReservation',
                request_serializer=mcp__pb2.WatchReservationRequest.SerializeToString,
                response_deserializer=mcp__pb2.ReservationEvent.FromString,
                _registered_method=True)
        self.ReleaseMachine = channel.unary_unary(
                '/mcp.v1.TestflingerControl/ReleaseMachine',
                request_serializer=mcp__pb2.ReleaseMachineRequest.SerializeToString,
                response_deserializer=mcp__pb2.ReleaseMachineResponse.FromString,
                _registered_method=True)
        self.ListReservations = channel.unary_unary(
                '/mcp.v1.TestflingerControl/ListReservations',
                request_serializer=mcp__pb2.ListReservationsRequest.SerializeToString,
                response_deserializer=mcp__pb2.ListReservationsResponse.FromString,
                _registered_method=True)
        self.BuildDebianPackage = channel.unary_unary(
                '/mcp.v1.TestflingerControl/BuildDebianPackage',
                request_serializer=mcp__pb2.BuildDebianPackageRequest.SerializeToString,
                response_deserializer=mcp__pb2.JobHandle.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/mcp.v1.TestflingerControl/GetJob',
                request_serializer=mcp__pb2.GetJobRequest.SerializeToString,
                response_deserializer=mcp__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.WatchJob = channel.unary_stream(
                '/mcp.v1.TestflingerControl/WatchJob',
                request_serializer=mcp__pb2.WatchJobRequest.SerializeToString,
                response_deserializer=mcp__pb2.JobEvent.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/mcp.v1.TestflingerControl/CancelJob',
                request_serializer=mcp__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=mcp__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.ListHosts = channel.unary_unary(
                '/mcp.v1.TestflingerControl/ListHosts',
                request_serializer=mcp__pb2.ListHostsRequest.SerializeToString,
                response_deserializer=mcp__pb2.ListHostsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/mcp.v1.TestflingerControl/HealthCheck',
                request_serializer=mcp__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=mcp__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class TestflingerControlServicer:
    """============================================================
    TestflingerControl — gRPC service definition

    Authentication: every RPC requires a bearer token in the
    gRPC metadata header:

    Authorization: Bearer <token>

    Tokens are static secrets provisioned out-of-band (env vars,
    vault injection).  The server returns UNAUTHENTICATED if the
    header is missing or wrong, PERMISSION_DENIED if the token
    lacks privileges for the requested operation.
    ============================================================

    """

    def ReserveMachine(self, request, context):
        """---- Machine provisioning (testflinger) ----

        Request a machine from the testflinger lab pool.
        Returns a reservation_id immediately; provisioning is async
        and may take minutes.  The required fields are:
        - queue: testflinger queue (target machine id, e.g. "oem-hp-wolf")
        - image: OS image name (e.g. "ubuntu-24.04", "noble")
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservation(self, request, context):
        """Poll the status of a reservation.  When state == READY the
        response contains the machine's ip_address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchReservation(self, request, context):
        """Server-stream reservation events until the machine is READY
        (or provisioning fails).  Preferred over polling — the server
        pushes status updates as they happen.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseMachine(self, request, context):
        """Release a reserved machine back to the pool.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListReservations(self, request, context):
        """List machines currently reserved by the caller's token.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildDebianPackage(self, request, context):
        """---- Build execution ----

        Build a Debian package from source.
        Clones repo_url at git_ref on a named host, then runs
        dpkg-buildpackage.  Returns a job_id; stream logs with WatchJob.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """---- Job management ----

        Poll the status/result of a job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchJob(self, request, context):
        """Server-stream log chunks and status updates for a job until
        it completes (or the client cancels the stream).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel a running job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHosts(self, request, context):
        """---- Housekeeping ----

        List machines this proxy can directly reach (pre-provisioned
        or always-on hosts, not testflinger pool).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Liveness probe — no auth required.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestflingerControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveMachine,
                    request_deserializer=mcp__pb2.ReserveMachineRequest.FromString,
                    response_serializer=mcp__pb2.ReserveMachineResponse.SerializeToString,
            ),
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=mcp__pb2.GetReservationRequest.FromString,
                    response_serializer=mcp__pb2.GetReservationResponse.SerializeToString,
            ),
            'WatchReservation': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchReservation,
                    request_deserializer=mcp__pb2.WatchReservationRequest.FromString,
                    response_serializer=mcp__pb2.ReservationEvent.SerializeToString,
            ),
            'ReleaseMachine': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseMachine,
                    request_deserializer=mcp__pb2.ReleaseMachineRequest.FromString,
                    response_serializer=mcp__pb2.ReleaseMachineResponse.SerializeToString,
            ),
            'ListReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListReservations,
                    request_deserializer=mcp__pb2.ListReservationsRequest.FromString,
                    response_serializer=mcp__pb2.ListReservationsResponse.SerializeToString,
            ),
            'BuildDebianPackage': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildDebianPackage,
                    request_deserializer=mcp__pb2.BuildDebianPackageRequest.FromString,
                    response_serializer=mcp__pb2.JobHandle.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=mcp__pb2.GetJobRequest.FromString,
                    response_serializer=mcp__pb2.GetJobResponse.SerializeToString,
            ),
            'WatchJob': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchJob,
                    request_deserializer=mcp__pb2.WatchJobRequest.FromString,
                    response_serializer=mcp__pb2.JobEvent.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=mcp__pb2.CancelJobRequest.FromString,
                    response_serializer=mcp__pb2.CancelJobResponse.SerializeToString,
            ),
            'ListHosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHosts,
                    request_deserializer=mcp__pb2.ListHostsRequest.FromString,
                    response_serializer=mcp__pb2.ListHostsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=mcp__pb2.HealthCheckRequest.FromString,
                    response_serializer=mcp__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcp.v1.TestflingerControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcp.v1.TestflingerControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestflingerControl:
    """============================================================
    TestflingerControl — gRPC service definition

    Authentication: every RPC requires a bearer token in the
    gRPC metadata header:

    Authorization: Bearer <token>

    Tokens are static secrets provisioned out-of-band (env vars,
    vault injection).  The server returns UNAUTHENTICATED if the
    header is missing or wrong, PERMISSION_DENIED if the token
    lacks privileges for the requested operation.
    ============================================================

    """

    @staticmethod
    def ReserveMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/ReserveMachine',
            mcp__pb2.ReserveMachineRequest.SerializeToString,
            mcp__pb2.ReserveMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/GetReservation',
            mcp__pb2.GetReservationRequest.SerializeToString,
            mcp__pb2.GetReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.v1.TestflingerControl/WatchReservation',
            mcp__pb2.WatchReservationRequest.SerializeToString,
            mcp__pb2.ReservationEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseMachine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/ReleaseMachine',
            mcp__pb2.ReleaseMachineRequest.SerializeToString,
            mcp__pb2.ReleaseMachineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/ListReservations',
            mcp__pb2.ListReservationsRequest.SerializeToString,
            mcp__pb2.ListReservationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildDebianPackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/BuildDebianPackage',
            mcp__pb2.BuildDebianPackageRequest.SerializeToString,
            mcp__pb2.JobHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/GetJob',
            mcp__pb2.GetJobRequest.SerializeToString,
            mcp__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcp.v1.TestflingerControl/WatchJob',
            mcp__pb2.WatchJobRequest.SerializeToString,
            mcp__pb2.JobEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/CancelJob',
            mcp__pb2.CancelJobRequest.SerializeToString,
            mcp__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/ListHosts',
            mcp__pb2.ListHostsRequest.SerializeToString,
            mcp__pb2.ListHostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcp.v1.TestflingerControl/HealthCheck',
            mcp__pb2.HealthCheckRequest.SerializeToString,
            mcp__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
